CREATE TABLE  customer (
 id  INT(11) NOT NULL auto_increment,
 first_name  VARCHAR(45) DEFAULT NULL,
 last_name  VARCHAR(45)DEFAULT NULL,
 email  VARCHAR(45) DEFAULT NULL,
PRIMARY KEY( id )
) ENGINE=INNODB AUTO_INCREMENT=1 CHARSET=latin1;